[project]
name = "trickcal-couponstance"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=25.1.0",
    "discord-webhook>=1.4.1",
    "environs>=14.3.0",
    "filetype>=1.2.0",
    "httpx[socks]>=0.28.1",
    "loguru>=0.7.3",
    "nodriver>=0.48.1",
    "orjson>=3.11.4",
    "python-dateutil>=2.9.0.post0",
]
